config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#index'

  namespace :user do
    resources :sessions, only: %i[index create]
    delete 'session', to: 'sessions#destroy'

    get 'all', to: 'users#index'
    get ':id', to: 'users#show'
    get ':id/serials_by_status', to: 'users#fetch_user_serials'
    post 'update_avatar', to: 'users#update_avatar'
    patch 'edit', to: 'users#update'
    delete ':id/delete', to: 'users#destroy'
  end

  get 'serials', to: 'serials#index'

  get 'tags', to: 'tags#index'
  get 'genres', to: 'genres#index'
  get 'actors', to: 'actors#index'
  get 'countries', to: 'countries#index'
  get 'serials/:id', to: 'serials#show'
  get 'seasons', to: 'seasons#get_serial_seasons'
  get 'season/:id', to: 'seasons#index'
  get 'episode/:id', to: 'episodes#index'
  get 'episode/:id/comments', to: 'episodes#episode_comments'

  post 'serials/:id/add_genre', to: 'genres#add_genre'
  post 'serials/:id/add_tag', to: 'tags#add_tag'
  post 'serials/:id/add_actor', to: 'actors#add_actor'
  post 'serials/:id/change_rate', to: 'ratings#create'
  post 'serials/:id/add_to_favourite', to: 'favourites#create'
  post 'serials/:id/remove_from_favourite', to: 'favourites#destroy'
  post 'serials/:id/update_view_status', to: 'serials#add_view_status'
  post 'episode/:id/create_comment', to: 'comments#create'
  patch 'serials/:id/edit', to: 'serials#update'

  delete 'serials/:id/delete_genre', to: 'genres#delete_genre'
  delete 'serials/:id/delete_tag', to: 'tags#delete_tag'
  delete 'serials/:id/delete_actor', to: 'actors#delete_actor'


  devise_for :users,
    controllers: {
      registrations: 'user/registrations',
      passwords: 'user/passwords'
    },
    path_names: {
      registration: 'new'
    }

  match '*path', to: 'pages#index', via: :all
end

app/models/serial.rb
# frozen_string_literal: true

require 'elasticsearch/model'

class Serial < ApplicationRecord # :nodoc:
  # requirements

  require 'date'

  # image uploader

  mount_uploader :image, SerialImageUploader

  # connecting elasticsearch

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  # elasticsearch settings

  settings do
    mappings dynamic: false do
      indexes :title, type: :string, analyzer: :english
      indexes :description, type: :text, analyzer: :english
    end
  end

  index_name([Rails.env, base_class.to_s.pluralize.underscore].join('_'))

  # associations

  has_many :seasons, dependent: :destroy

  has_many :favourites
  has_many :users_fav, through: :favourites, source: :user

  has_many :ratings
  has_many :users_rating, through: :ratings, source: :user

  has_many :view_statuses
  has_many :users_status, through: :view_statuses, source: :user

  has_many :serial_genres
  has_many :genres, through: :serial_genres

  has_many :serial_actors
  has_many :actors, through: :serial_actors

  has_many :serial_tags
  has_many :tags, through: :serial_tags

  belongs_to :country

  # validations

  validates :title, presence: { message: 'must be filled.' }
  validates :year_of_premiere, length: { is: 4, message: 'can be only 4 digits long.' }, numericality: { only_integer: true, greater_than_or_equal_to: 1933, less_than_or_equal_to: Date.current.year }
  validates :description, presence: { message: 'must be added.' }

  # scopes

  scope :order_by_year, -> { order(year_of_premiere, asc) }
  scope :order_by_title, -> { order(title, asc) }
  scope :search_by_country, ->(id) { where country_id: id }

  # methods

  def filled_stars
    grades = Rating.where(serial_id: id).map(&:value)
    grades.empty? ? 0 : grades.inject(0) { |sum, grade| sum + grade } / grades.length
  end

  def empty_stars
    5 - filled_stars
  end

  def current_user_stars(user_id)
    mark = Rating.find_by(serial_id: id, user_id: user_id)
    mark.nil? ? 0 : mark.value
  end

  def current_user_empty_stars(user)
    5 - current_user_stars(user)
  end

  def self.tagged_with(name)
    Tag.find_by_tag_name(name).serials
  end

  def self.with_genre_filter(name)
    Genre.find_by_title(name).serials
  end

  # def is_favourite?(user)
  #   user.includes(:serials_fav).where(serial_id: id).present? true : false
  # end
end

# Serial.import

app/controllers/serials_controller.rb
# frozen_string_literal: true

class SerialsController < ApplicationController # :nodoc:
  before_action :set_serial, only: %i[show edit update destroy add_view_status]
  before_action :set_view_status, only: %i[add_view_status]

  # GET /serials
  # GET /serials.json
  def index
    if params[:tag].present?
      @serials = Serial.tagged_with(params[:tag])
    elsif params[:query].present?
      @serials = Serial.search(params[:query]).records
    elsif params[:genre].present?
      @serials = Serial.with_genre_filter(params[:genre])
    else
      @serials = Serial.all
    end
    render json: { items: @serials }
  end

  # GET /serials/1
  # GET /serials/1.json
  def show
    is_fav = @serial.users_fav.where(id: params[:user_id]).present?
    view_status = null ||= ViewStatus.find_by(serial_id: @serial.id, user_id: params[:user_id])

    render json: {
      serial: @serial,
      seasons: @serial.seasons,
      tags: @serial.tags,
      genres: @serial.genres,
      actors: @serial.actors,
      isFav: is_fav,
      overall_rating: @serial.filled_stars,
      user_rating: @serial.current_user_stars(params[:user_id]),
      view_status: view_status
    }
  end

  # GET /serials/new
  def new
    @serial = Serial.new
  end

  # GET /serials/1/edit
  def edit; end

  # POST /serials
  # POST /serials.json
  def create
    @serial = Serial.new(serial_params)

    respond_to do |format|
      if @serial.save
        format.html { redirect_to @serial, notice: 'Serial was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # add serial view status
  def add_view_status
    @serial.users_status.destroy(User.find_by_id(params[:user_id])) unless @status.nil?

    if params[:view_status].empty?
      render json: { message: 'err' }
    else
      @new_status = ViewStatus.new(serial_id: @serial.id, user_id: params[:user_id], status: params[:view_status])
      if @new_status.save
        render json: {
          message: 'view status changed'
        }, status: 200
      else
        render json: {
          message: 'err'
        }, status: 400
      end
    end
  end

  # PATCH/PUT /serials/1
  # PATCH/PUT /serials/1.json
  def update
    if @serial.update(
      country_id: params[:countryId],
      image: params[:serialImage],
      title: params[:title],
      year_of_premiere: params[:yearOfPremiere],
      description: params[:description]
    )
      render json: {
        message: 'Successfully updated.'
      }
    else
      render json: {
        message: 'Failed to update.'
      }, status: 400
    end
  end

  # DELETE /serials/1
  # DELETE /serials/1.json
  def destroy
    @serial.destroy
    respond_to do |format|
      format.html { redirect_to serials_url, notice: 'Serial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_serial
    @serial = Serial.find(params[:id])
  end

  def set_view_status
    @status = ViewStatus.find_by(serial_id: params[:id], user_id: params[:user_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def serial_params
    params.require(:serial).permit(:id, :title, :year_of_premiere, :description, :country_id, :image)
  end
end

app/helpers/serials_helper.rb
# frozen_string_literal: true

module SerialsHelper # :nodoc:

  def user_view_status
    status = ViewStatus.find_by(serial_id: @serial.id, user_id: current_user.id)
    return status.status unless status.nil?

    "You didn't mention your view status on this serial yet."
  end

  def fav_button
    if current_user.present?
      return link_to 'Remove from favourites', serial_favourite_path(@serial, current_user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' unless Favourite.where(user_id: current_user.id, serial_id: @serial.id).empty?

      link_to 'Add to favourites', serial_favourites_path(@serial), method: :create, class: 'btn btn-light'
    end
  end

  def country_of_origin
    return 'Wasn\'t mentioned.' if @serial.country_id.blank?

    Country.find_by(id: @serial.country_id).country_name
  end

  def tag_links(tag)
    link_to tag.tag_name, tag_path(tag: tag.tag_name), class: 'badge badge-light'
  end

  def genres_links(genre)
    link_to genre.title + " (#{genre.serials.count})", genre_path(genre.title), id: "#{genre.title} genre", class: 'genre-filter-link'
  end
end

app/views/serials/_add_actor_to_serial.html.erb
<%= form_for @serial, class: 'form-row', url: { action: 'add_actor' } do |f| %>

  <%= f.fields_for :serial_actors do |fsg| %>
    <%= fsg.fields_for :actors do |fg| %>
      <%= select_tag 'actor_select', options_from_collection_for_select(Actor.all, :id, ->(act){ "#{act.first_name} #{act.last_name}" }), id: 'actor_select', prompt: 'Select', class: 'user-dropdown' %>
    <% end %>
  <% end %>

  <%= f.submit 'Add actor', class: "btn btn-light user-button" %>
<% end %>

app/views/serials/_add_genre_to_serial.html.erb
<%= form_for @serial, class: 'form-row', url: { action: 'add_genre' } do |f| %>
  <%= f.fields_for :serial_genres do |fsg| %>
    <%= fsg.fields_for :genres do |fg| %>
      <%= select_tag 'genre_select', options_from_collection_for_select(Genre.all, :id, :title), id: 'genre_select', prompt: 'Select', class: 'user-dropdown' %>
    <% end %>
  <% end %>

  <%= f.submit 'Add genre', class: "btn btn-light user-button" %>
<% end %>

app/views/serials/_add_tag_to_serial.html.erb
<%= form_for @serial, class: 'form-row', url: { action: 'add_tag' } do |f| %>
  <%= f.fields_for :serial_tags do |fsg| %>
    <%= fsg.fields_for :tags do |fg| %>
      <%= fg.text_field 'tag', id: 'tag_select', prompt: 'Select', class: 'user-dropdown' %>
    <% end %>
  <% end %>

  <%= f.submit 'Add tag', class: "btn btn-light user-button" %>
<% end %>

app/views/serials/_add_user_view_status.html.erb
<%= form_for @serial, class: 'form-row', url: { action: 'add_view_status', controller: 'serials' } do |f| %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= select_tag 'view_status', options_for_select(['Will be watching', 'Watching right now', 'Finished watching']), prompt: 'Select', class: 'user-dropdown' %>

  <%= f.submit 'Add status', class: "btn btn-light user-button" %>
<% end %>

app/views/serials/_form.html.erb
<%= form_with(model: serial, local: true, class: 'serial-form') do |form| %>
  <%= render "layouts/errors", resource: serial %>

  <div class="form-group col-md-6">
    <div class="field">
      <%= form.file_field :image %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= form.label :year_of_premiere %>
      <%= form.select :year_of_premiere, options_for_select(1933..2019), class: 'form-control' %>
    </div>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :country_id, "Country of origin" %><br />
    <%= form.collection_select(:country_id, Country.all, :id, :country_name, prompt: 'Select')  %>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, size: '85x8', class: "form-control"  %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-secondary" %>
  </div>

<% end %>

app/views/serials/_serial_card.html.erb
<div class="card serial-card">
  <%= image_tag serial.image.url(:thumb), class: "card-img-top", alt: serial.title if serial.image? %>
  <div class="card-body">
    <div class="card-content">
      <h5 class="card-title"><%= serial.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= serial.year_of_premiere %></h6>
      <% if serial.tags.any? %>
          <% serial.tags.each do |tag| %>
            <span class="badge badge-light serial-tag"><%= tag.tag_name %></span>
          <% end %>
      <% end %>
      <p class="card-text"><%= truncate(serial.description, :length => 120) %></p>
    </div>

    <div class="card-links">
      <%= link_to 'Show', serial, class: "btn btn-light" %>
      <% if current_user&.admin? %>
        <%= link_to 'Edit', edit_serial_path(serial), class: "btn btn-light" %>
        <%= link_to 'Destroy', serial, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light" %>
      <% end %>
    </div>
  </div>
</div>

app/views/serials/_serial_search_form.html.erb
<%= form_tag serials_path, method: :get, class: 'form-row' do %>
    <%= text_field_tag :query, params[:query], placeholder: 'Search', class: "form-group col-md-11 serials-search-field" %>
    <%= submit_tag 'Search', class: "btn btn-light col-md-1" %>
<% end %>

app/views/serials/edit.html.erb
<h1>Editing Serial</h1>

<%= render 'form', serial: @serial %>

<br>

<%= link_to 'Show', @serial %> |
<%= link_to 'Back', serials_path %>

app/views/serials/index.html.erb
<br>

<div class="serials-head">
  <div class="">
    <h1>Serials</h1>
  </div>
  <br>
  <div class="serials-search">
    <%= render 'serial_search_form' %>
  </div>
</div>

<br>

<div class="serials-body">
  <div class="filters">
    <div class="filter tag-filter">
      <p>Tags</p>
      <% Tag.all.each do |tag| %>
        <%=raw tag_links(tag) %>
      <% end %>
      <%= link_to 'all', serials_path, class: 'badge badge-light' %>
    </div>

    <div class="filter genre-filter">
      <p>Genres</p>
      <ul class="list-group list-group-flush">
        <% Genre.all.each do |genre| %>
          <li class="list-group-item" >
            <%=raw genres_links(genre) %>
          </li>
        <% end %>
        <li class="list-group-item">
          <%= link_to 'All', serials_path, class: 'genre-filter-link' %>
        </li>
      </ul>
    </div>
  </div>

  <div class="serials-container">
    <% @serials.each do |serial| %>
      <%= render 'serial_card', serial: serial %>
    <% end %>
  </div>
</div>

<br>

<% if current_user&.admin? %>
  <%= link_to 'New Serial', new_serial_path, class: "btn btn-light" %>
<% end %>

app/views/serials/new.html.erb
<h1>New Serial</h1>

<%= render 'form', serial: @serial %>

<%= link_to 'Back', serials_path %>

app/views/serials/show.html.erb
<div class="serial-container">
  <div class="serial-img-description-container">
    <div class="serial-preview">
      <%= image_tag @serial.image.url(:thumb), class: "card-img-top", alt: @serial.title if @serial.image? %>
    </div>
    <div class="serial-body">
      <div class="title-block">
        <h2 class="display-5"><%= @serial.title %></h2>
        <div class="title-fav">
          <%= fav_button %>
        </div>
      </div>

      <p>
        <strong>Year of premiere:</strong>
        <%= @serial.year_of_premiere %>
      </p>

      <p>
        <strong>County of origin:</strong>
        <%= country_of_origin %>
      </p>

      <p><%= @serial.description %></p>

      <div class="serial-info">
        <div class="main-info info-div">
          <% if @serial.genres.any? %>
            <p class="serial-info-header">Genres</p>
              <% @serial.genres.each do |genre| %>
                <span class="badge badge-light">
                  <%= genre.title %>
                  <% if current_user&.admin? %>
                    <%= link_to('delete', delete_genre_serial_path(genre_id: genre.id), method: :delete) %>
                  <% end %>
                </span>
              <% end %>
          <% end %>

          <% if @serial.tags.any? %>
            <p class="serial-info-header">Tags</p>
              <% @serial.tags.each do |tag| %>
                <span class="badge badge-light">
                  <%= tag.tag_name %>
                  <% if current_user&.admin? %>
                    <%= link_to('delete', delete_tag_serial_path(tag_id: tag.id), method: :delete) %>
                  <% end %>
                </span>
              <% end %>
          <% end %>

          <% if @serial.actors.any? %>
            <p class="serial-info-header">Cast</p>
              <% @serial.actors.each do |actor| %>
                <span class="badge badge-light">
                  <%= actor.first_name %>
                  <%= actor.last_name %>
                  <% if current_user&.admin? %>
                    <%= link_to('delete', delete_actor_serial_path(actor_id: actor.id), method: :delete) %>
                  <% end %>
                </span>
              <% end %>
          <% end %>

          <br>
          <br>
          <br>

          <% if current_user&.admin?  %>
            <%= render 'add_genre_to_serial' %>
            <%= render 'add_actor_to_serial' %>
            <%= render 'add_tag_to_serial' %>
          <% end %>
        </div>

        <div class="serial-rating-status info-div">
          <div class = 'rating'>
            <p>Overall rating </p>
            <% @serial.filled_stars.times do %>
              <span><%= icon('fas', 'star') %></span>
            <% end %>
            <% @serial.empty_stars.times do %>
              <span><%= icon('far', 'star') %></span>
            <% end %>
          </div>
          <% if current_user.present? %>
            <div class = 'rating'>
                <p>My rating </p>
                <% counter = 0 %>
                <% @serial.current_user_stars(current_user).times do |i| %>
                <% counter += 1 %>
                  <%= button_to user_ratings_path(user_id: current_user.id, serial_id: @serial.id, value: counter), method: :post, class: 'star-btn', value: "#{ counter }" do %>
                    <%= icon('fas', 'star', class: 'rating-star', id: "#{ counter }") %>
                  <% end %>
                <% end %>
                <% @serial.current_user_empty_stars(current_user).times do |i| %>
                <% counter += 1 %>
                  <%= button_to user_ratings_path(user_id: current_user, serial_id: @serial, value: counter), method: :post, action: 'create', class: 'star-btn', value: "#{ counter }" do %>
                    <%= icon('far', 'star', class: 'rating-star', id: "#{ counter }") %>
                  <% end %>
                <% end %>
            </div>
          <% end %>

          <div class="status">
            <% if current_user.present? %>
              <p>View status: <span><%= user_view_status %></span></p>
              <%= render 'add_user_view_status' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <hr class="my-4">
  <h3>Seasons:</h3>
  <ul class="list">
    <% @serial.seasons.ordered_by_count.each do |season| %>
      <li class="list-item">
        <%= link_to serial_season_path(@serial, season), class: "badge badge-light" do %>
          Season <%= season.season_number %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <% if current_user&.admin? %>
    <%= link_to 'Edit', edit_serial_path(@serial), class: "btn btn-light" %>
  <% end %>
  <%= link_to 'Back', serials_path, class: "btn btn-light" %>
</div>