config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#index'

  namespace :user do
    resources :sessions, only: %i[index create]
    delete 'session', to: 'sessions#destroy'

    get 'all', to: 'users#index'
    get ':id', to: 'users#show'
    get ':id/serials_by_status', to: 'users#fetch_user_serials'
    post 'update_avatar', to: 'users#update_avatar'
    patch 'edit', to: 'users#update'
    delete ':id/delete', to: 'users#destroy'
  end

  get 'serials', to: 'serials#index'

  get 'tags', to: 'tags#index'
  get 'genres', to: 'genres#index'
  get 'actors', to: 'actors#index'
  get 'countries', to: 'countries#index'
  get 'serials/:id', to: 'serials#show'
  get 'seasons', to: 'seasons#get_serial_seasons'
  get 'season/:id', to: 'seasons#index'
  get 'episode/:id', to: 'episodes#index'
  get 'episode/:id/comments', to: 'episodes#episode_comments'

  post 'serials/:id/add_genre', to: 'genres#add_genre'
  post 'serials/:id/add_tag', to: 'tags#add_tag'
  post 'serials/:id/add_actor', to: 'actors#add_actor'
  post 'serials/:id/change_rate', to: 'ratings#create'
  post 'serials/:id/add_to_favourite', to: 'favourites#create'
  post 'serials/:id/remove_from_favourite', to: 'favourites#destroy'
  post 'serials/:id/update_view_status', to: 'serials#add_view_status'
  post 'episode/:id/create_comment', to: 'comments#create'
  patch 'serials/:id/edit', to: 'serials#update'

  delete 'serials/:id/delete_genre', to: 'genres#delete_genre'
  delete 'serials/:id/delete_tag', to: 'tags#delete_tag'
  delete 'serials/:id/delete_actor', to: 'actors#delete_actor'


  devise_for :users,
    controllers: {
      registrations: 'user/registrations',
      passwords: 'user/passwords'
    },
    path_names: {
      registration: 'new'
    }

  match '*path', to: 'pages#index', via: :all
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # :nodoc:
  acts_as_token_authenticatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # connecting avatar uploader

  mount_uploader :avatar, AvatarUploader

  # associations declaration

  has_many :favourites
  has_many :serials_fav, through: :favourites, source: :serial, dependent: :destroy

  has_many :ratings
  has_many :serials_rating, through: :ratings, source: :serial, dependent: :destroy

  has_many :view_statuses
  has_many :serials_status, through: :view_statuses, source: :serial, dependent: :destroy

  has_many :comments
  has_many :episodes, through: :comments, dependent: :destroy

  belongs_to :countries, optional: true

  # devise settings

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable

  # requirements

  require 'date'

  # validations declaration

  validate :date_validation

  # validations functions

  def date_validation
    return unless date_of_birth && date_of_birth > Date.today

    errors.add(:date_of_birth, "Date of birth musn't be greater than the current date.")
  end

  # omniauth settings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.first_name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = '123456'
    end
  end

  # scopes

  scope :admins, -> { where admin: true }

  scope :ordered_by_first_name, -> { order(first_name: :asc) }
  scope :ordered_by_last_name, -> { order(last_name: :asc) }

  # methods

  def user_serials(need)
    case need
    when 'will'
      Serial.joins(:view_statuses).where(view_statuses: { user_id: id, status: 'Will be watching' })
    when 'now'
      Serial.joins(:view_statuses).where(view_statuses: { user_id: id, status: 'Watching right now' })
    when 'done'
      Serial.joins(:view_statuses).where(view_statuses: { user_id: id, status: 'Finished watching' })
    else
      Serial.joins(:view_statuses).where(view_statuses: { user_id: id })
    end
  end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    user = User.find_by_id(params[:id])

    if !user.valid_password?(params[:password])
      return render json: {
        message: 'Incorrect current password.'
      }, status: 400
    end

    if params[:new_password].present?
      if params[:new_password] == params[:new_password_confirmation]
        if user.update(
          password: params[:new_password]
        )
          render json: {
            message: 'Password changed successfully.'
          }, status: 200

          user.send_password_change_notification
        else
          render json: {
            message: 'Something went wrong.'
          }, status: 400
        end
      else
        render json: {
          message: 'Incorrect password confirmation.'
        }, status: 400
      end
    else
      return render json: {
        message: 'New password can\'t be empty.'
      }, status: 400
    end
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /users
  def create
    if params[:password] == params[:password_confirmation]
      user = User.new(
                        email: params[:email],
                        password: params[:password],
                        first_name: params[:first_name],
                        last_name: params[:last_name],
                        date_of_birth: params[:date_of_birth],
                        gender: params[:gender],
                        country_id: params[:country_id]
                      )

      if user.save
        session[:user_id] = user.id
        render json: {
          message: 'created',
          user: user
        }, status: :ok
      else
        render json: {
          message: 'error',
          err: user.errors.full_messages
        }, status: 406
      end
    else
      render json: {
        message: 'user can\'t be created',
        err: 'incorrect password confirmation'
      }, status: 406
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < ApplicationController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :get_current_user

  def index
    if @current_user == nil
      render json: {
        message: 'user session not found'
      }, status: :not_found
    else
      render json: {
        currentUser: @current_user
      }, status: 200
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /user/sessions
  def create
    user = User.find_by_email(params[:email])

    if user&.valid_password?(params[:password])
      session[:user_id] = user.id
      render json: user.as_json, status: :created
    else
      head(:unauthorized)
    end
  end

  # DELETE /user/session
  def destroy
    session.delete(:user_id)
    render json: {
      session: session[:user_id],
      status: :deleted,
      notice: 'sessions destroyed'
    }
  end

  # protected

  def user_id
    session[:user_id]
  end

  def get_current_user
    @current_user = User.find_by_id(user_id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/users_controller.rb
# frozen_string_literal: true

class User::UsersController < ApplicationController # :nodoc:
  # before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy fetch_user_serials]

  # GET /users
  # GET /users.json
  def index
    @users = params[:need] == 'adm' ? User.admins : User.all
    render json: {
      users: @users
    }
  end

  # GET /users/1
  # GET /users/1.json
  def show
    country = @user.country_id.present? ? Country.find_by_id(@user.country_id).country_name : nil
    favourites = @user.serials_fav.records

    render json: {
      user: @user,
      country: country,
      favourites: favourites
    }
  end

  def fetch_user_serials
    serials = @user.user_serials(params[:status])

    render json: {
      status: params[:status],
      serials: serials
    }
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    user = User.find_by_id(params[:id])
    emailChanged = user.email != params[:email] ? true : false

    if user.update(
                    email: params[:email],
                    first_name: params[:first_name],
                    last_name: params[:last_name],
                    date_of_birth: params[:date_of_birth],
                    gender: params[:gender],
                    country_id: params[:country_id]
                  )
      render json: {
        message: 'User was successfully updated.',
        user: user
      }
      if emailChanged
        user.send_email_changed_notification
        user.send_confirmation_instructions
      end
    else
      render json: {
        message: 'something went wrong.'
      }
    end
  end

  def update_avatar
    user = User.find_by_id(params[:id])

    if params[:avatar] == 'undefined'
      nil
    else
      if user.update(avatar: params[:avatar])
        render json: {
          message: 'Avatar was successfully loaded.'
        }, status: :ok
      else
        render json: {
          message: 'Avatar could not be updated.'
        }, status: 400
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy!
    render json: {
      message: 'user destroyed'
    }, status: 200
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :date_of_birth, :country_id, :avatar)
  end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController # :nodoc:
  # before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy fetch_user_serials]

  # GET /users
  # GET /users.json
  def index
    @users = params[:need] == 'adm' ? User.admins : User.all
    render json: {
      users: @users
    }
  end

  # GET /users/1
  # GET /users/1.json
  def show
    country = @user.country_id.present? ? Country.find_by_id(@user.country_id).country_name : nil
    favourites = @user.serials_fav.records

    render json: {
      user: @user,
      country: country,
      favourites: favourites
    }
  end

  def fetch_user_serials
    serials = @user.user_serials(params[:status])

    render json: {
      status: params[:status],
      serials: serials
    }
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy!
    render json: {
      message: 'user destroyed'
    }, status: 200
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :date_of_birth, :country_id, :avatar)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper # :nodoc:
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= render "layouts/errors", resource: user %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth, start_year: 1980, end_year: Date.current.year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<br>

<% if current_user&.admin? %>
  <%= link_to 'All', users_path, class: "btn btn-light" %>
  <%= link_to 'Admins', users_path(need: 'adm'), class: "btn btn-light" %>
<% end %>

<br><br>

  <div class="list-group">
    <% @users.ordered_by_first_name.each do |user| %>
      <div class="list-group-item user-container">
        <div class="">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= user.first_name %> <%= user.last_name %></h5>
          </div>
          <p class="mb-1"><%= user.email %></p>
        </div>
        <div class="">
          <%= link_to 'Show', user, class: 'btn btn-light' %>
          <% if current_user&.admin? %>
            <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-light' %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %></td>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="user-card">

  <div class="user-avatar">
    <%= image_tag @user.avatar.url(:thumb) if @user.avatar? %>
  </div>

  <div class="user-body">

    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>

    <p>
      <strong>Gender:</strong>
      <%= @user.gender %>
    </p>

    <p>
      <strong>Date of birth:</strong>
      <%= @user.date_of_birth %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <% if @user&.country_id %>
      <p>
        <strong>Country:</strong>
        <%= Country.where(id: @user.country_id).first.country_name %>
      </p>
    <% end %>

    <% if current_user.present? && current_user.confirmed_at == nil %>
      <p>Please confirm your email.</p>
      <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(@user) %><br />
    <% end %>


    <% if current_user&.admin? %>
      <p>
        <strong>Admin:</strong>
        <%= @user.admin %>
      </p>
    <% end %>

    <br>

      <strong>Favourite serials:</strong>
      <% if @user.serials_fav.any? %>
        <ul>
          <% @user.serials_fav.each do |serial| %>
            <li>
              <%= link_to serial do %>
                <%= serial.title %>
              <% end %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>Nothing was added to favourites yet. </p>
      <% end %>

      <div class="">
        <%= link_to 'Will watch', user_path(@user, need: 'will'), class: "btn btn-secondary" %>
        <%= link_to 'Watching', user_path(@user, need: 'now'), class: "btn btn-secondary" %>
        <%= link_to 'Completed', user_path(@user, need: 'done'), class: "btn btn-secondary" %>
        <%= link_to 'All', @user, class: "btn btn-secondary" %>
      </div>

      <br>

      <ul>
        <% @user_serials.each do |serial| %>
          <li>
            <%= link_to serial do %>
              <%= serial.title %>
            <% end %>
          </li>
        <% end %>
      </ul>

  </div>

</div>

<br>

<%= link_to 'Back', users_path %>
<% if current_user.present? && current_user == @user || current_user&.admin? %>
  | <%= link_to 'Edit', edit_user_registration_path(@user) %>
<% end %>