config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#index'

  namespace :user do
    resources :sessions, only: %i[index create]
    delete 'session', to: 'sessions#destroy'

    get 'all', to: 'users#index'
    get ':id', to: 'users#show'
    get ':id/serials_by_status', to: 'users#fetch_user_serials'
    post 'update_avatar', to: 'users#update_avatar'
    patch 'edit', to: 'users#update'
    delete ':id/delete', to: 'users#destroy'
  end

  get 'serials', to: 'serials#index'

  get 'tags', to: 'tags#index'
  get 'genres', to: 'genres#index'
  get 'actors', to: 'actors#index'
  get 'countries', to: 'countries#index'
  get 'serials/:id', to: 'serials#show'
  get 'seasons', to: 'seasons#get_serial_seasons'
  get 'season/:id', to: 'seasons#index'
  get 'episode/:id', to: 'episodes#index'
  get 'episode/:id/comments', to: 'episodes#episode_comments'

  post 'serials/:id/add_genre', to: 'genres#add_genre'
  post 'serials/:id/add_tag', to: 'tags#add_tag'
  post 'serials/:id/add_actor', to: 'actors#add_actor'
  post 'serials/:id/change_rate', to: 'ratings#create'
  post 'serials/:id/add_to_favourite', to: 'favourites#create'
  post 'serials/:id/remove_from_favourite', to: 'favourites#destroy'
  post 'serials/:id/update_view_status', to: 'serials#add_view_status'
  post 'episode/:id/create_comment', to: 'comments#create'
  patch 'serials/:id/edit', to: 'serials#update'

  delete 'serials/:id/delete_genre', to: 'genres#delete_genre'
  delete 'serials/:id/delete_tag', to: 'tags#delete_tag'
  delete 'serials/:id/delete_actor', to: 'actors#delete_actor'


  devise_for :users,
    controllers: {
      registrations: 'user/registrations',
      passwords: 'user/passwords'
    },
    path_names: {
      registration: 'new'
    }

  match '*path', to: 'pages#index', via: :all
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord # :nodoc:
  belongs_to :user
  belongs_to :episode
  has_many :comments

  validates :content, presence: { message: "musn't be empty." }

  scope :episode_comments_list, ->(episode_id, comment_id) { where episode_id: episode_id, comment_id: comment_id }
end

app/models/episode.rb
# frozen_string_literal: true

class Episode < ApplicationRecord # :nodoc:
  belongs_to :season

  has_many :comments
  has_many :users, through: :comments

  def episode_number
    num = id.to_s.remove(season_id.to_s)
    num.empty? ? season_id : num
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController # :nodoc:
  before_action :find_commentable, only: :create

  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create(user_id: params[:user_id], episode_id: params[:id], comment_id: params[:comment_id], content: params[:content])
    render json: {
      message: 'comment created'
    }
  end

  def destroy
    @episode = Episode.find_by id: params[:episode_id]
    @comment = Comment.find_by id: params[:id]
    @episode.comments.destroy(@comment)

    respond_to do |format|
      format.html { redirect_to season_episode_path(@episode.season, @episode), notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  def comment_params
    params[:comment].permit(:user_id, :episode_id, :content, :comment_id)
  end

  def find_commentable
    if params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    else
      @commentable = Episode.find_by_id(params[:episode_id])
    end
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController # :nodoc:
  before_action :set_episode, only: %i[index destroy episode_comments]

  def index
    render json: {
      episode: @episode,
      episodeIndex: Episode.where(season_id: @season.id).find_index(@episode) + 1,
      serialTitle: @season.serial.title,
      seasonIndex: Season.where(serial_id: @season.serial.id).find_index(@season) + 1
    }
  end

  def episode_comments
    comments = []
    Comment.where(episode_id: @episode.id).each do |comment|
      comments.push({
        id: comment.id,
        created_at: comment.created_at,
        comment_id: comment.comment_id,
        content: comment.content,
        user: User.find_by_id(comment.user_id)
        })
    end
    render json: {
      comments: comments
    }
  end

  private

  def set_episode
    @episode = Episode.find(params[:id])
    @season = Season.find(@episode.season.id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper # :nodoc:
end

app/helpers/episodes_helper.rb
# frozen_string_literal: true

module EpisodesHelper # :nodoc:
end

app/views/episodes/comments/_comment_item.html.erb
<div class="card card-body">
    <div class="card-user-info">
      <div class="comment-user-email">
        <h5 class="card-title"><%= User.where(id: comment.user_id).first.email %></h5>
      </div>
      <div class="comment-button">
        <% if current_user&.admin? %>
          <%= link_to 'Delete comment', episode_comment_path(@episode, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light"  %>
        <% end %>
      </div>
    </div>
    <p class="card-text"><%= comment.content %></p>
    <p>
      <%= comment.created_at.strftime("%F") %> <%= comment.created_at.strftime("%T") %>
    </p>

    <% if comment.comment_id.blank? %>
      <% Comment.episode_comments_list(@episode.id, comment.id).each do |reply| %>
        <%= render "episodes/comments/comment_item", comment: reply %>
      <% end %>
      <% if current_user.present? %>
        <div class="card reply-card">
          <%= render "episodes/comments/form", comment_id: comment.id %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/episodes/comments/_form.html.erb
<%= form_for([@episode, @episode.comments.build]) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :episode_id, value: @episode.id %>
  <%= f.hidden_field :comment_id, value: local_assigns[:comment_id] %>

  <p><%= local_assigns[:comment] %></p>

  <label for="create-comment-text-area">
    <% if local_assigns[:comment_id].present? %>
      <h5>Reply</h5>
    <% end %>
    <%= current_user.email %>
  </label>
  <p>
    <%= f.text_area :content, size: '85x4', class: "form-control", id: "create-comment-text-area" %>
  </p>

  <div class="actions">
    <% if local_assigns[:comment_id].present? %>
      <%= f.submit 'Reply', class: "btn btn-light" %>
    <% else %>
      <%= f.submit class: "btn btn-light" %>
    <% end %>
  </div>
<% end %>